spring:
  application:
    name: multi-datasource-preview-add-cache
  datasource:
    source:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/message_system
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: SourceConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
    replica:
      hikari:
        jdbc-url: jdbc:mysql://localhost:13306/message_system
        username: dev_user
        password: dev_password
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: ReplicaConnectionPool
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 60000
        connection-timeout: 30000
  jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always # prod: never
  data:
    redis:
      host: localhost
      port: 16379
      repositories:
        enabled: false
#logging:
#  level:
#    com.zaxxer.hikari: debug
